### login
POST http://localhost:3001/auth/signin
Content-Type: application/json

{
  "email": "matthieu@gmail.com",
  "password": "aspirateur"
}

> {%
    client.global.set("auth_token", response.body.token.val);
%}

### Create new invoice
POST http://localhost:3001/invoices/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "darty_equipement.pdf",
  "content": "bought some furniture for the living room of the new appartment",
  "url": "https://power80.files.wordpress.com/2012/07/facture.png",
  "pretaxValue": "316",
  "VAT": "2.4",
  "idFrom": 1,
  "idTo": 2,
  "date": "2023-09-16",
  "debit": true
}

### Get invoice 1
GET http://localhost:3001/invoices/13
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### Get invoice 1
GET http://localhost:3001/invoices/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Update invoice
PUT http://localhost:3001/invoices/13
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "13",
  "title": "UPDATED TITLE",
  "url": "https://power80.files.wordpress.com/2012/07/facture.png",
  "pretaxValue": "316",
  "VAT": "2.4",
  "date": "2023-09-16"
}
