### Create User
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "email": "matthieu@gmail.com",
  "name": "Matthieu Porte",
  "password": "aspirateur"
}

### Create User
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "email": "vincent@gmail.com",
  "name": "Vincent Porte",
  "password": "lisbonne"
}

### Create User
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "email": "jordan@gmail.com",
  "name": "Jordan Porte",
  "password": "minecraft"
}
